baseURL: https://marcusgame.dev # todo: change site url.
title: Marcus Szabo # todo: change site name.
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  image: /images/banner.png
  logo: MarcusLogo.png # todo: add your custom logo to static/
  subtitle: Marcus Szabo's Portfolio. # todo: change default subtitle for your website.
  copyright: All rights reserved. # todo: set your copyright type.
  author: Marcus Szabo # todo: set your full name.
  dontShowSource: false # please, do not do this :)
  portfolio:
    columns:
      desktop:
        games: 4
        design: 6
        default: 3
      mobile:
        default: 2
        games: 3
  socials:
    # todo: change these links.
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:marcus.szabo@outlook.com'
      landing: true
    - icon: 'fab fa-artstation fa-lg'
      url: 'https://www.artstation.com/marcusszabo8'
      landing: true
    - icon: 'fab fa-twitter fa-lg'
      url: 'https://twitter.com/Pyranthian0'
    - icon: 'fab fa-linkedin-in fa-lg'
      url: 'https://www.linkedin.com/in/marcus-szabo-76b77a19b/'
  homepage: "/work" # homepage link, mostly same with menu.main[0]
  specialPages:
    - work
    - archive
  bypassWelcomePage: true # redirects "/" to "homepage" when it's true.
  disableWelcomePageBackground: false # disables the background image on the homepage
  plausible: '' # todo: set your plausible id.
  disableRadius: false
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false
  hideExif: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: work
      url: /work/
      weight: 1
    - name: games
      url: /tags/games/
      weight: 2
    - name: art
      url: /tags/art/
      weight: 3
    - name: design
      url: /tags/design/
      weight: 4
    - name: about
      url: /about/
      weight: 5
